import { callApi } from "../../utils/cloud";
Page({
  data:{sharedMode:false,transcriptionProviders:[{value:"openai",label:"OpenAI Transcription 兼容"},{value:"tencent",label:"腾讯云实时转写 + 异步回退"}],transcription:{provider:"openai",providerLabel:"OpenAI Transcription 兼容",baseUrl:"https://api.openai.com/v1",apiKey:"",apiSecret:"",appId:"",region:"ap-guangzhou",model:"gpt-4o-transcribe",language:"zh",diarization:false},summary:{provider:"openai-compatible",baseUrl:"https://api.deepseek.com",apiKey:"",model:"deepseek-v4-flash"}},
  async onLoad(){try{const s=await callApi<any>("getProviderConfigStatus");this.setData({sharedMode:!!s.shared});if(s.transcriptionConfig)this.setData({transcription:{...this.data.transcription,...s.transcriptionConfig,apiKey:"",apiSecret:""}});if(s.summaryConfig)this.setData({summary:{...this.data.summary,...s.summaryConfig,apiKey:""}});}catch{}},
  changeTranscriptionProvider(e:any){const p=this.data.transcriptionProviders[Number(e.detail.value)];this.setData({transcription:{...this.data.transcription,provider:p.value,providerLabel:p.label,baseUrl:p.value==="openai"?"https://api.openai.com/v1":"https://asr.tencentcloudapi.com",model:p.value==="openai"?"gpt-4o-transcribe":"16k_zh"}});},
  inputField(e:any){const {scope,key}=e.currentTarget.dataset;this.setData({[`${scope}.${key}`]:e.detail.value});},
  testTranscription(){if(this.data.sharedMode)return;this.test("transcription",this.data.transcription);},testSummary(){if(this.data.sharedMode)return;this.test("summary",this.data.summary);},
  async test(kind:string,config:any){wx.showLoading({title:"测试中"});try{await callApi("testProviderConfig",{kind,config});wx.showToast({title:"连接成功"});}catch(e:any){wx.showModal({title:"连接失败",content:e.message,showCancel:false});}finally{wx.hideLoading();}},
  async save(){if(this.data.sharedMode){wx.showToast({title:"已使用管理员配置",icon:"none"});return;}wx.showLoading({title:"保存中"});try{await callApi("saveProviderConfig",{transcription:this.data.transcription,summary:this.data.summary});wx.showToast({title:"已安全保存"});}catch(e:any){wx.showModal({title:"保存失败",content:e.message,showCancel:false});}finally{wx.hideLoading();}},back(){wx.navigateBack();}
});
